version: "3"

services:
  client_elo_aram:
    depends_on:
      - server_elo_aram
    ports:
      - "3000:3000"
    build:
      context: ./client
      dockerfile: Dockerfile
  server_elo_aram:
    ports:
      - "8080:8080"
    build:
      context: ./server
      dockerfile: Dockerfile
